export type UserRole =
  | 'PLATFORM_OWNER'
  | 'SUPER_ADMIN'
  | 'DEPARTMENT_ADMIN'
  | 'COUNSELLOR'
  | 'STUDENT'
  | 'FACULTY_MENTOR'
  | 'PROGRAM_ADMIN'
  | 'TRAINER'
  | 'PLACEMENT_COORDINATOR';

export const STAFF_ROLES: UserRole[] = [
  'FACULTY_MENTOR',
  'PROGRAM_ADMIN',
  'TRAINER',
  'PLACEMENT_COORDINATOR',
  'DEPARTMENT_ADMIN',
  'COUNSELLOR',
];
